[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
  | versioneer.py
  | esmlab_regrid/_version.py
)/
'''
skip-string-normalization = true

[build-system]
requires = ["setuptools", "wheel", "versioneer"]
build-backend = "setuptools.build_meta:__legacy__"
